apiVersion: v1
kind: Service
metadata:
  name: {{ include "cse.fullname" . }}
  labels:
    {{- include "cse.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cse.service.type }}
  ports:
    - port: {{ .Values.cse.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cse.selectorLabels" . | nindent 4 }}
