apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cse.fullname" . }}-database-secret
  labels:
    {{- include "cse.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.database.password | quote }}