{{- if not .Values.cse.auth.spnego.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cse.fullname" . }}-user-secret
  labels:
    app.kubernetes.io/name: {{ include "cse.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  application-users.properties: |-
{{ .Values.cse.auth.spnego.config.applicationUsers | default "" | indent 4 }}
  application-roles.properties: |-
{{ .Values.cse.auth.spnego.config.applicationRoles | default "" | indent 4 }}
{{- end }}
