cse:
  replicaCount: 1

  image:
    repository: rstevens198238/cloud-storage-explorer
    tag: "latest"
    pullPolicy: IfNotPresent

  imagePullSecrets: []

  env:
    - name: DB_USER
      value: postgres
    - name: DB_PORT
      value: "5432"
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: cse-database-secret
          key: POSTGRES_PASSWORD
    - name: DB_HOST
      value: cse-postgres-cluster.cse-test.svc.cluster.local
    - name: JAVA_OPTS
      value: "-Djboss.bind.address.management=0.0.0.0 -Xms2g -Xmx6g"

  auth:
    spnego:
      enabled: false
      config:
        applicationUsers: |
          admin=b4e2efbdbb678152c8a7351b90627cf0
          joe=d1e8f6d5a06d1cbec2a47283f6ebe0b3
          david=a56b31d8654b2c1522cdfdec8e771ede
          adele=8da80885e04704788a6b7f8284b4a4e6
          adrian=d48cbbf77d05efc23f7385bf030e4e12
          kcassell=15571782e219bb30217a6bb97222b1c6
        applicationRoles: |
          admin=StorageExplorerUsers,StorageExplorerAdmins
          joe=StorageExplorerUsers
          david=StorageExplorerDriveAdmins
          adele=StorageExplorerUsers,StorageExplorerDriveAdmins
          adrian=StorageExplorerAdmins
          kcassell=StorageExplorerUsers,StorageExplorerAdmins

  podAnnotations: {}

  podLabels: {}

  podSecurityContext:
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
    runAsNonRoot: true

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  readOnlyRootFilesystem: false

  service:
    type: ClusterIP
    port: 8080

  ingress:
    enabled: true
    manual:
      cert: |-
        -----BEGIN CERTIFICATE-----
        # your cert here (keep indentation exactly like this)
        -----END CERTIFICATE-----
      key: |-
        -----BEGIN PRIVATE KEY-----
        # your key here (keep indentation exactly like this)
        -----END PRIVATE KEY-----

    className: "nginx"
    annotations: {}
    hosts:
      - host: ddc-rm-steve
        paths:
          - path: /storage-explorer
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - ddc-rm-steve
        secretName: cse-ingress-secret

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  resources:
    requests:
      cpu: "512m"
      memory: "3Gi"
    limits:
      cpu: "4"
      memory: "6Gi"

  livenessProbe:
    httpGet:
      path: /health/live
      port: 9990

  readinessProbe:
    httpGet:
      path: /health/live
      port: 9990

  volumeMounts:
    - name: standalone-xml
      mountPath: /opt/wildfly/standalone/configuration/standalone.xml
      subPath: standalone.xml
      readOnly: true
      configMap: standalone-xml

    - name: application-auth
      mountPath: /opt/wildfly/standalone/configuration/application-users.properties
      subPath: application-users.properties
      readOnly: true
      spnegoOnly: true
      secret: cse-user-secret

    - name: application-auth
      mountPath: /opt/wildfly/standalone/configuration/application-roles.properties
      subPath: application-roles.properties
      readOnly: true
      spnegoOnly: true
      secret: cse-user-secret

  volumes:
    - name: standalone-xml
      configMap:
        name: standalone-xml

    - name: application-auth
      secret:
        secretName: cse-user-secret
        items:
          - key: application-users.properties
            path: application-users.properties
          - key: application-roles.properties
            path: application-roles.properties

  nodeSelector: {}

  tolerations: []

  affinity: {}

database:
  enabled: true
  replicaCount: 1
  port: 5432

  image:
    repository: postgres
    tag: "14"
    pullPolicy: Always

  name: storexp
  user: postgres
  password: dbpassword
  existingSecret: cse-database-secret

  storage: 10Gi
  storageClass: dynamic-local-path

  podAnnotations: {}
  podLabels: {}

  podSecurityContext: {}
  securityContext: {}

  volumeMounts: []

  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"