{{- if and .Values.cse.ingress.enabled (gt (len .Values.cse.ingress.tls) 0) (not .Values.cse.ingress.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cse.fullname" . }}-ingress-secret
  labels:
    {{- include "cse.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.cse.ingress.manual.cert | required "ingress.manual.cert is required" | b64enc }}
  tls.key: {{ .Values.cse.ingress.manual.key | required "ingress.manual.key is required" | b64enc }}
{{- end }}