{{- if .Values.database.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cse.fullname" . }}-postgres
  labels:
    {{- include "cse.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.database.port | default 5432 }}
      name: postgres
  selector:
    {{- include "cse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cse.fullname" . }}-postgres-cluster
  labels:
    {{- include "cse.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.database.port | default 5432 }}
      targetPort: {{ .Values.database.port | default 5432 }}
      protocol: TCP
      name: postgres
  selector:
    {{- include "cse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}