{{- if .Values.cse.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cse.serviceAccountName" . }}
  labels:
    {{- include "cse.labels" . | nindent 4 }}
  {{- with .Values.cse.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.cse.serviceAccount.automount }}
{{- end }}
