name: Publish Helm Chart

on:
  push:
    paths:
      - 'cse/**'
      - '.github/workflows/helm-publish.yml'

jobs:
  helm-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write    # needed to push to the repo

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Package chart
        run: |
          mkdir -p packaged
          helm package cse -d packaged

      - name: Move chart to docs
        run: |
          mkdir -p docs
          cp packaged/*.tgz docs/

      - name: Rebuild Helm repo index
        run: |
          helm repo index docs --url https://mdaca.github.io/cse-helm --merge docs/index.yaml

      - name: Commit and push updated chart
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          git commit -m "Update Helm chart [auto]"
          git push