name: Update Helm Chart Release

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Get version from commit message
        id: get_commit_message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MESSAGE"
          VERSION_TYPE=$(echo "$COMMIT_MESSAGE" | grep -oP '\[(major|minor|patch)\]' | tr -d '[]')
          echo "VERSION_TYPE=${VERSION_TYPE:-none}" >> $GITHUB_ENV

      - name: Get branch name
        run: |
          CURRENT_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          echo "BRANCH_NAME=$CURRENT_BRANCH" >> $GITHUB_ENV

      - name: Update Helm Chart Version
        run: |
          cd chart/cse
          CURRENT_VERSION=$(grep '^version:' Chart.yaml | awk '{print $2}')
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"

          if [[ "$VERSION_TYPE" != "none" ]]; then
            if [[ "$VERSION_TYPE" == "major" ]]; then
              MAJOR=$((MAJOR + 1)); MINOR=0; PATCH=0
            elif [[ "$VERSION_TYPE" == "minor" ]]; then
              MINOR=$((MINOR + 1)); PATCH=0
            elif [[ "$VERSION_TYPE" == "patch" ]]; then
              PATCH=$((PATCH + 1))
            fi

            NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
            sed -i "s/^version: .*/version: ${NEW_VERSION}/" Chart.yaml
            echo "Updated chart version to $NEW_VERSION"
          else
            echo "No version update (version: $CURRENT_VERSION)"
          fi

      - name: Package and update Helm repo index
        run: |
          cd chart
          helm package cse --destination cse
          helm repo index cse --url https://mdaca.github.io/cse-helm/chart/cse --merge cse/index.yaml

      - name: Commit chart changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add chart/cse/*
          git commit -m "Update Helm chart version for $BRANCH_NAME" || echo "Nothing to commit"

      - name: Push changes
        run: |
          git push origin HEAD:$BRANCH_NAME